from __future__ import annotations

import json
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Protocol

from coding_agent.config import ModelConfig


@dataclass(frozen=True)
class ModelResponse:
    """Normalized text and token counts returned by a language model."""

    # The actual text generated by the model.
    text: str

    # Number of input tokens processed for this response. Some providers may
    # omit usage data, so the provider-independent default is zero.
    prompt_tokens: int = 0

    # Number of new tokens generated by the model for this response.
    completion_tokens: int = 0


class Model(Protocol):
    """Interface the agent uses without depending on a model provider."""

    def generate(self, messages: list[dict[str, str]]) -> ModelResponse:
        """Generate the next response from a chat history."""
        ...


@dataclass
class OllamaModel:
    """Small synchronous adapter for Ollama's local chat endpoint."""

    config: ModelConfig
    timeout: float = 300.0

    def generate(self, messages: list[dict[str, str]]) -> ModelResponse:
        payload = json.dumps(
            {
                "model": self.config.name,
                "messages": messages,
                "stream": False,
                "options": {
                    "temperature": self.config.temperature,
                    "num_ctx": self.config.context_length,
                },
            }
        ).encode("utf-8")
        request = urllib.request.Request(
            f"{self.config.base_url.rstrip('/')}/api/chat",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                data = json.load(response)
        except urllib.error.HTTPError as error:
            raise RuntimeError(f"Ollama returned HTTP {error.code}") from error
        except urllib.error.URLError as error:
            raise RuntimeError(
                f"Could not connect to Ollama at {self.config.base_url}"
            ) from error
        except (json.JSONDecodeError, UnicodeDecodeError) as error:
            raise RuntimeError("Ollama returned invalid JSON") from error

        try:
            text = data["message"]["content"]
        except (KeyError, TypeError) as error:
            raise RuntimeError("Ollama response is missing message.content") from error
        if not isinstance(text, str):
            raise RuntimeError("Ollama message.content must be a string")

        return ModelResponse(
            text=text,
            prompt_tokens=int(data.get("prompt_eval_count", 0)),
            completion_tokens=int(data.get("eval_count", 0)),
        )
